<div class="shadow-box super-margin-box super-padding-box">
    <?php

    use Zend\Form\Element;

    $this->headTitle($title);
    ?>
    <h1>Edit <mark><?php echo $this->escapeHtml($destination->title); ?></mark></h1>
    <?php

    $form->setAttribute('action', $this->url('destination', ['action' => 'edit', 'id' => $this->id ]) );
    $form->prepare();

    echo $this->form()->openTag($form);

    foreach ($form as $element) { ?>

        <div class="form-group">
            <?php echo $this->formLabel($element);
            echo $this->formElement($element);       // <-- Magic!
            echo $this->formElementErrors($element);
            ?>
        </div>
    <?php }
    echo $this->form()->closeTag();
    ?>
</div>
