<div class="shadow-box super-margin-box super-padding-box">
    <?php

    use Zend\Form\Element;

    $this->headTitle($title);
    ?>
    <h1>Edit <mark><?php echo $this->escapeHtml($destination->title); ?></mark></h1>
    <?php

    $form->setAttribute('action', $this->url('destination', ['action' => 'edit', 'id' => $this->id ]) );
    $form->prepare();

    echo $this->form()->openTag($form);

    foreach ($form as $element) { ?>

        <div class="form-group">
            <?php echo $this->formLabel($element);
            echo $this->formElement($element);       // <-- Magic!
            echo $this->formElementErrors($element);
            ?>
        </div>
    <?php } ?>
    <hr>
    Available images:
    <div class="row">
        <?php foreach ($destination->picture as $key => $image) { ?>
            <div class="col-md-3">
                <img class="img-responsive img-thumbnail" src="<?php echo $this->s3Link($image['name'],'roomister'); ?>">
                <hr>
                <a class="btn btn-warning ajax-action" href="/destination/edit/<?php print $id ?>/del-img/<?php print $key ?>"><i class="fa fa-trash-o"></i></a>
                <script type="text/javascript">
                    $('.ajax-action').click( function(e){
                        // e.preventDefault();
                        console.log($(this).attr('href'));
                    })
                </script>
            </div>
        <?php } ?>
    </div>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
